name: Docker Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build -t abhijeetsacumen/flask_memes .
    - name: Push to Dockerhub
      run: docker push abhijeetsacumen/flask_memes:latest